import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Future World - Nextjs layout",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <header>
        <nav>
          <ul>
            <li>Home</li>
            <li>Store</li>
          </ul>
        </nav>
      </header>
      </body>
    </html>
  );
}
