import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Future World - Nextjs layout",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <header>
        <nav>
          <ul>
            <Link href="/">
              <li>Home</li>
            </Link>

            <Link href="/store">
            <li>Store</li>            
            </Link>
            
            <Link href="/hello_world">
            <li>Hello world</li>            
            </Link>
          </ul>
        </nav>
      </header>
      </body>
    </html>
  );
}
